"""This module contains configurations such as function names and regex patterns for the log handler"""

LOG_PATTERNS = {
    "GM:": "processGMActions",
    "chat :": "processChat",
    "formatlog:sendmail": "processSendMail",
    "formatlog:rolelogin": "processRoleLogin",
    "formatlog:rolelogout": "processRoleLogout",
    "formatlog:trade": "processTrade",
    "formatlog:task": "process_task",  # done
    "formatlog:die": "processDie",
    "formatlog:faction": "process_create_faction",  # done
    "formatlog:upgradefaction": "process_upgrade_faction",  # done
    "formatlog:gshop_trade": "processGShopTrade",
    "建立了队伍": "process_create_party",
    "成为队员": "process_join_party",
    "脱离队伍": "process_leave_party",
    "丢弃包裹": "processDropItem",
    "丢弃装备": "processDropEquipment",
    "拣起金钱": "process_pick_up_money",  # done
    "丢弃金钱": "processDiscardMoney",
    "从NPC购买了": "processBuyItem",
    "卖店": "processSellItem",
    "得到金钱": "processGetMoney",
    "拣起": "processPickupItem",
    "升级到": "processLevelUp",
    "花掉金钱": "processSpendMoney",
    "消耗了sp": "processSpConsume",
    "技能": "processSkillLevelUp",
    "制造了": "process_craft_item",  # done
    "采集得到": "process_mine",  # done
    "孵化了宠物蛋": "processPetEggHatch",
    "还原了宠物蛋": "processPetEggRestore",
    "组队拣起用户": "pickupTeamMoney",
    "得到经验": "process_exp_sp",  # done
}

TASK_PATTERNS = {
    "DeliverItem": r"Item id\s*=\s*(\d+),\s*Count\s*=\s*(\d+)",
    "DeliverByAwardData": r"gold\s*=\s*(\d+),\s*exp\s*=\s*(\d+),\s*sp\s*=\s*(\d+),\s*reputation\s*=\s*(\d+)",
}

REGEX_PATTERNS = {
    "startActivity": "GM %d started the activity %d.",
    "stopActivity": "GM %d stopped the activity %d.",
    "toggleInvincibility": "GM %d toggled invincibility state. Current state : %d.",
    "toggleInvisibility": "GM %d toggled invisibility state. Current state : %d.",
    "dropMonsterSpawner": "GM %d dropped monster spawner with ID : %d.",
    "playerDisconnect": "Player %d was disconnected. Disconnect type : %d.",
    "activateTrigger": "GM %d activated the trigger %d.",
    "cancelTrigger": "GM %d canceled the trigger %d.",
    "createMonster": "GM %d created %d monster(s) of type %d and ID %d,",
    "attemptMoveToPlayer": "GM %d attempted to move to player %d.",
    "moveToPlayer": "GM %d moved to player %d at position (%f, %f, %f).",
    "movePlayer": "GM %d moved player %d to position (%f, %f, %f).",
    "command": "The GM with Role ID %d executed internal command %d.",
    "process_mine": r"用户(\d+)采集得到(\d+)个(\d+)",
    "process_create_faction": r"roleid=(\d+):factionid=(\d+)",
    "process_upgrade_faction": r"factionid=(\d+):master=(\d+):money=(\d+):level=(\d+)",
    "deleteFaction": "(Action type: %s) An attempt to delete the faction ID %d was detected!",
    "joinFaction": "(Type: %s) The Role ID %d joined the Faction ID %d",
    "promoteRoleInFaction": "(Type: %s) The Role ID %d was promoted by his superior (ID %d) in Faction ID %d. New position: %d",
    "deleteRoleFromFaction": "(Type: %s) Role with ID %d was deleted from Faction ID %d. Role: %d",
    "leaveFaction": "(Type: %s) The Role ID %d just left the Faction ID %d, his position was: %d",
    "pickupTeamMoney": "Role ID %d picked up money (%d) dropped by Role ID %d they both were in a Party.",
    "process_create_party": r"用户(\d+)建立了队伍\((\d+),\d+\)",
    "process_join_party": r"用户(\d+)成为队员\((\d+),\d+\)",
    "process_leave_party": r"用户(\d+)脱离队伍\((\d+),\d+\)",
    "petEggHatch": "The Role ID %d hatched the pet egg ID %d.",
    "petEggRestore": "The Role ID %d restored a pet and received the pet egg ID %d.",
    "process_craft_item": r"用户(\d+).*?(\d+).*?(\d+).*?(\d+).*?(\d+).*?(\d+).*?(\d+).*?(\d+)",
    "die": "Role %d died. Death type: %d. Attacker: %d.",
    "spendMoney": "The Role ID %d spent %d money.",
    "spConsume": "The Role ID %d consumed %d sp.",
    "skillLevelUp": "The Role ID %d leveled up the skill ID %d to level %d.",
    "sendMail": "Timestamp: %d, The Role ID %d just sent a mail to role ID %d. Mail ID: %d. Mail size: %d. Money sent: %d. Item ID: %d. Item count: %d. Mail position: %d.",
    "roleLogout": "The account ID %d logged out with the role ID %d",
    "roleLogin": "The account ID %d logged in with the role ID %d",
    "dropItem": "The Role ID %d discarded %d unit(s) of item ID %d",
    "process_pick_up_money": r"用户(\d+)拣起金钱(\d+)",
    "discardMoney": "The Role ID %d discarded %d money",
    "buyItem": "The Role ID %d bought %d unit(s) of the item ID: %d from a NPC",
    "sellItem": "The Role ID %d sold %d unit(s) of the item ID: %d to a NPC",
    "getMoney": "The Role ID %d received %d money",
    "trade": "Role %d traded with role %d. Money exchanged: %d from role %d and %d from role %d. Role %d traded %s items. And Role %d traded %s items.",
    "dropEquipment": "The Role ID %d discarded his equipment of ID %d",
    "pickupItem": "The Role ID %d picked up %d unit(s) of item %d (discarded by role ID %d)",
    "purchaseFromAuction": "The Role ID %d purchased %d item(s) from gshop, spent %d unit(s) of cash, remaining balance: %d",
    "process_task": r"roleid=(\d+):taskid=(\d+)",
    "receiveItemFromTask": "The Role ID %d received %d unit(s) of the item ID %d from the task ID %d",
    "receiveTaskReward": "The Role ID %d completed the task ID %d and received as reward: gold = %d, exp = %d, sp = %d, reputation = %d",
    "levelUp": "The Role ID %d leveled up to level %d. Current money: %s. Playtime: %s.",
    "gShopTrade": "User ID %d performed a trade with the following details: Magic Number: %d, Order ID: %d, Item ID: %d, Expire: %d, Item Count: %d, Cash Needed: %d, Cash Left: %d, GUID 1: %d, GUID 2: %d",
    "process_exp_sp": r"用户(\d+)得到经验 (\d+)/(\d+)",
}
